#pragma once
#ifndef BLOCK_ENUM_H_INCLUDED
#define BLOCK_ENUM_H_INCLUDED

enum BlockType {
	BLOCK_AIR,
	BLOCK_IRON_BLOCK,
	BLOCK_REDSTONE_WIRE,
	BLOCK_REDSTONE_BLOCK,
	BLOCK_REPEATER,
	BLOCK_REDSTONE_TORCH,
	BLOCK_TORCH,
};

enum BlockOrientation { TOP, RIGHT, BOT, LEFT };

#endif // !BLOCK_ENUM_H_INCLUDED
